//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HotelPMS.rc
//
#define IDCANCEL2                       3
#define TDC_BUTTON_ADD                  3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_HotelPMSTYPE                129
#define IDD_DLG_MESSAGE                 130
#define IDR_BOOKINGSTS                  130
#define IDD_DLG_SEARCH                  131
#define IDD_DLG_RESERVATION             132
#define IDR_TOOLBAR_BST                 133
#define IDB_BMP_BOOKINGSTS              135
#define IDC_CURSOR_ARW                  136
#define IDC_CURSOR_CRE                  138
#define IDC_CURSOR_CW1                  139
#define IDC_CURSOR_CW2                  140
#define IDC_CURSOR_HRZ                  141
#define IDC_CURSOR_LDN                  142
#define IDC_CURSOR_RDN                  143
#define IDC_CURSOR_VRT                  144
#define IDB_BITMAP_INFOTOOLBAR          145
#define IDR_MENU_SCH_CIN                146
#define IDR_MENU_SCH_INH                147
#define IDR_MENU_SCH_COT                148
#define IDR_MENU_BST                    149
#define IDD_DLG_CHECKIN                 150
#define IDR_MENU_RSV_ROM                150
#define IDD_DLG_INHOUSE                 151
#define IDD_DLG_CHECKOUT                152
#define IDD_DIALOG_ROOMCHARGE           153
#define IDD_DIALOG_COPYSELECT           154
#define IDD_DIALOG1                     155
#define IDD_DIALOG_CATEGORYSELECT       155
#define IDD_DIALOG_CHARGEDETAIL         156
#define IDD_DIALOG_CLIENTINFO           157
#define IDD_DIALOG_DATEPICKER           158
#define IDD_DIALOG_OPERATOR             159
#define IDD_DIALOG_BRANCH               160
#define IDD_DIALOG_FACILITY             161
#define IDD_DIALOG_SELECTRATEPLAN       162
#define IDD_DIALOG_EQUIPMENTTYPE        163
#define IDD_DIALOG_EQUIPMENTINFO        164
#define IDD_DIALOG_CASHIER              165
#define IDD_DIALOG_PRODUCTSEL           166
#define IDD_DIALOG_CATEGORY             167
#define IDD_DIALOG_PRODUCT              168
#define IDD_DIALOG_CURRENCYCVS          169
#define IDD_DIALOG_PAYMENT              170
#define IDD_DIALOG_ADDDEPOSIT           171
#define IDD_DIALOG_TRANSFERDST          172
#define IDD_DIALOG_ROOMSELECT           173
#define IDR_MENU_CIN_ROM                174
#define IDD_DIALOG_CURRENCYRATE         175
#define IDD_DLG_NIGHTAUDIT              176
#define IDR_MENU_NGT_ADT                177
#define IDD_DIALOG2                     178
#define IDD_DLG_HOUSEKEEPING            178
#define IDD_DIALOG_TRAVELAGENT          179
#define IDD_DIALOG_CREDITCARD           180
#define IDD_DIALOG_CREDITCARDCOM        180
#define IDD_DIALOG3                     181
#define IDD_DIALOG_EMPLOYEE             181
#define IDD_DIALOG_LOGIN                182
#define IDD_DIALOG_CHANGEPASSWORD       183
#define IDD_DIALOG_SEARCHCLIENT         184
#define IDD_DIALOG4                     185
#define IDD_DIALOG_DUTY                 185
#define IDD_DIALOG5                     186
#define IDD_DIALOG_MAKETSEGMENT         186
#define IDC_STATIC_MSG                  1000
#define IDC_STATIC_RSVPANEL             1001
#define IDC_TAB_KIND                    1002
#define IDC_STATIC_CINPANEL             1003
#define IDC_STATIC_INHPANEL             1004
#define IDC_STATIC_COTPANEL             1005
#define IDC_STATIC_RSV_ID               1006
#define IDC_EDIT_RSV_ID                 1007
#define IDC_STATIC_RSV_NAME             1008
#define IDC_COMBO_RSV_BOOKIGFROM        1009
#define IDC_EDIT_RSV_NAME               1010
#define IDC_STATIC_RSV_ARRIVALFR        1011
#define IDC_EDIT_RSV_ARRIVALFR          1012
#define IDC_EDIT_RSV_ARRIVALTO          1013
#define IDC_STATIC_RSV_ARRIVALTO        1014
#define IDC_STATIC_RSV_DEPARTUREFR      1015
#define IDC_EDIT_RSV_DEPARTUREFR        1016
#define IDC_BUTTON_RESEARCH             1017
#define IDC_EDIT_RSV_DEPARTURETO        1018
#define IDC_STATIC_BOOKINGID            1019
#define IDC_STATIC_RSV_DEPARTURETO      1020
#define IDC_STATIC_BOOKINGID2           1021
#define IDC_STATIC_RATEPLANNAME         1022
#define IDC_STATIC_BOOKINGPATH          1023
#define IDC_EDIT_FIRSTNAME              1024
#define IDC_STATIC_BOOKINGPATH2         1025
#define IDC_EDIT_LASTNAME               1025
#define IDC_STATIC_BOOKINGNAME          1026
#define IDC_EDIT_EMPLOYEECODE           1026
#define IDC_STATIC_RSV_BOOKINGFR        1027
#define IDC_STATIC_FIRSTARRIVAL         1028
#define IDC_STATIC_CLIENTRANK           1029
#define IDC_EDIT_FAMILYNAME             1030
#define IDC_STATIC_LASTDEPARTURE        1031
#define IDC_STATIC_CIN_ID               1032
#define IDC_STATIC_TELEPHONE1           1033
#define IDC_RADIO_PERSONAL              1034
#define IDC_STATIC_TELEPHONE2           1035
#define IDC_BUTTON_DEFAULT2             1036
#define IDC_STATIC_CLIENTTYPE           1037
#define IDC_TAB_DETAIL                  1038
#define IDC_TAB_RSV_DETAIL              1039
#define IDC_STATIC_INH_NAME             1040
#define IDC_RADIO_GROUP                 1041
#define IDC_STATIC_INH_ARRIVALFR        1042
#define IDC_EDIT_ADDRESS1               1043
#define IDC_STATIC_INH_ARRIVALTO        1044
#define IDC_EDIT_ADDRESS2               1045
#define IDC_STATIC_INH_DEPARTUREFR      1046
#define IDC_EDIT_ABBREVIATION           1047
#define IDC_EDIT_TELEPHONE1             1048
#define IDC_EDIT_CODE                   1048
#define IDC_EDIT_COMMENT                1048
#define IDC_EDIT_ABBREVIATION2          1049
#define IDC_EDIT_PRICE                  1049
#define IDC_EDIT_BRANCHCODE             1050
#define IDC_EDIT_READABLECODE           1050
#define IDC_STATIC_INH_DEPARTURETO      1051
#define IDC_EDIT_TELEPHONE3             1052
#define IDC_EDIT_EXTBOOKINGID           1053
#define IDC_EDIT_IDNUMBER               1054
#define IDC_EDIT_TELEPHONE2             1055
#define IDC_STATIC_INH_BOOKINGFR        1056
#define IDC_EDIT_IMMIGRATIONVISANO      1057
#define IDC_EDIT_FAXNUMBER              1058
#define IDC_EDIT_INH_ID                 1059
#define IDC_EDIT_CREDITCARDNO           1060
#define IDC_EDIT_EMAIL1                 1061
#define IDC_EDIT_INH_NAME               1062
#define IDC_EDIT_CREDITCARDTITLE        1063
#define IDC_EDIT_EMAIL2                 1064
#define IDC_EDIT_INH_ARRIVALFR          1065
#define IDC_EDIT_EMAIL3                 1065
#define IDC_EDIT_PASSOWRD               1065
#define IDC_EDIT_ZIPCODE                1066
#define IDC_EDIT_FIRSTARRIVAL           1067
#define IDC_EDIT_DATEOFBIRTH            1068
#define IDC_EDIT_INH_ARRIVALTO          1069
#define IDC_EDIT_EMPLOYMENTDATE         1069
#define IDC_EDIT_DATEOFISSUE            1070
#define IDC_EDIT_LASTDEPARTURE          1071
#define IDC_EDIT_DATEOFEXPIRE           1072
#define IDC_EDIT_INH_DEPARTUREFR        1073
#define IDC_EDIT_VISAEXPIREDATE         1074
#define IDC_STATIC_PANEL                1075
#define IDC_EDIT_CREDITCARDNO2          1076
#define IDC_EDIT_VALIDTHRU              1077
#define IDC_EDIT_INH_DEPARTURETO        1078
#define IDC_EDIT_FIRSTNAME_DETAIL       1079
#define IDC_COMBO_CIN_BOOKIGFROM        1080
#define IDC_EDIT_FAMILYNAME_DETAIL      1081
#define IDC_STATIC_CIN_ROOMNO           1082
#define IDC_EDIT_ARRIVALDATE            1083
#define IDC_EDIT_CIN_ROOMNO             1084
#define IDC_EDIT_LASTDEPARTURE2         1085
#define IDC_EDIT_DEPARTUREDATE          1086
#define IDC_STATIC_INH_ID               1087
#define IDC_EDIT_ARRIVALTIME            1088
#define IDC_STATIC_CIN_NAME             1089
#define IDC_EDIT_DEPARTURETIME          1090
#define IDC_EDIT_CIN_ID                 1091
#define IDC_CHECK_EARLYCI               1092
#define IDC_EDIT_CIN_NAME               1093
#define IDC_CHECK_LATECO                1094
#define IDC_STATIC_COT_ROOMNO           1095
#define IDC_EDIT_ADULTNUMBER            1096
#define IDC_STATIC_COT_ID               1097
#define IDC_EDIT_CHILDNUMBER            1098
#define IDC_STATIC_COT_NAME             1099
#define IDC_EDIT_ROOMCHANGE             1100
#define IDC_EDIT_ROOM                   1100
#define IDC_EDIT_COT_ROOMNO             1101
#define IDC_BUTTON_ROOM                 1102
#define IDC_STATIC_CIN_BOOKINGFR        1103
#define IDC_BUTTON_ROOMTYPE             1104
#define IDC_BUTTON_BOOKINGPATH          1105
#define IDC_EDIT_NOTE                   1106
#define IDC_COMBO_INH_BOOKIGFROM        1107
#define IDC_BUTTON_BOOKINGPATH2         1108
#define IDC_BUTTON_CANCEL               1109
#define IDC_SPIN_ADULTNUMBER            1110
#define IDC_STATIC_COT_BOOKINGFR        1111
#define IDC_SPIN_ADULTNUMBER2           1112
#define IDC_SPIN_ROOMCHANGE             1113
#define IDC_SPIN_CHILDNUMBER            1114
#define IDC_EDIT_COT_ID                 1115
#define IDC_BUTTON_CANCEL2              1116
#define IDC_EDIT_ROOMNUMBER             1117
#define IDC_EDIT_COT_NAME               1118
#define IDC_BUTTON_CANCEL3              1119
#define IDC_BUTTON_SEARCH               1120
#define IDC_SPIN_ROOMNUMBER             1121
#define IDC_COMBO_COT_BOOKIGFROM        1122
#define IDC_BUTTON_SEARCHDETAIL         1122
#define IDC_EDIT_NIGHTS                 1123
#define IDC_SPIN_NIGHTS                 1124
#define IDC_STATIC_DETAILSTS            1125
#define IDC_COMBO_ROOMTYPE              1126
#define IDC_STATIC_INFOSTS              1127
#define IDC_CHECK_SAMERESERVATION       1128
#define IDC_CHECK_ALL                   1129
#define IDC_COMBO_ROOMTYPE2             1130
#define IDC_COMBO_RATEPLANNAME          1131
#define IDC_COMBO_BOOKINGPATH           1132
#define IDC_STATIC_ROOMLIST             1133
#define IDC_STATIC_CINLIST              1134
#define IDC_COMBO_CLIENTRANK            1135
#define IDC_BUTTON_EXECCHECKIN          1136
#define IDC_COMBO_CLIENTRANK2           1136
#define IDC_COMBO_MARKETSEGMENT         1136
#define IDC_STATIC_RESERVATIONTYPE      1137
#define IDC_COMBO_BRANCH                1138
#define IDC_COMBO_FACILITY              1139
#define IDC_COMBO_FACILITYKIND          1140
#define IDC_COMBO_CATEGORY              1140
#define IDC_COMBO_EQUIPMENTTYPE         1141
#define IDC_COMBO_PRODUCTKIND           1141
#define IDC_TAB_BOOKINGPATH             1142
#define IDC_COMBO_PRODUCTKIND2          1142
#define IDC_COMBO_PRICEKIND             1142
#define IDC_COMBO_BUILDING              1143
#define IDC_COMBO_PRODUCTKIND3          1143
#define IDC_COMBO_TRANSFERORIGIN        1143
#define IDC_COMBO_WING                  1144
#define IDC_EDIT_PLANNAME               1145
#define IDC_COMBO_VIEW                  1146
#define IDC_EDIT_SALESTARTDATE          1147
#define IDC_COMBO_DIRECTION             1148
#define IDC_EDIT_SALEENDDATE            1149
#define IDC_COMBO_SIZE                  1150
#define IDC_COMBO_CHARGEKIND            1151
#define IDC_EDIT_PERSON                 1152
#define IDC_EDIT_AMOUNT1                1153
#define IDC_EDIT_AMOUNT2                1154
#define IDC_EDIT_AMOUNT3                1155
#define IDC_EDIT_AMOUNT4                1156
#define IDC_EDIT_AMOUNT5                1157
#define IDC_EDIT_AMOUNT6                1158
#define IDC_EDIT_AMOUNT7                1159
#define IDC_EDIT_AMOUNT8                1160
#define IDC_EDIT_AMOUNT9                1161
#define IDC_BUTTON_COPYALL              1162
#define IDC_EDIT_SALESTARTDATE2         1163
#define IDC_EDIT_ROOMNO                 1164
#define IDC_STATIC_APPLY                1165
#define IDC_BUTTON_UPDATE               1166
#define IDC_BUTTON_ADD                  1167
#define IDC_BUTTON_DELETE               1168
#define IDC_BUTTON_REFUND               1168
#define IDC_COMBO_CHARGETYPE            1169
#define IDC_BUTTON_ADD2                 1169
#define IDC_CHECK1                      1170
#define IDC_BUTTON_DELETE2              1170
#define IDC_CHECK_ATTRIBUTE             1170
#define IDC_CHECK_BASE                  1170
#define IDC_CHECK_ENABLESMOKE           1170
#define IDC_CHECK_ALLSELECT             1170
#define IDC_CHECK_OTA                   1170
#define IDC_CHECK_RSV_RSV               1170
#define IDC_CHECK_SALEENABLE            1171
#define IDC_CHECK_BASE2                 1171
#define IDC_CHECK_SECONDALY             1171
#define IDC_CHECK_REAL                  1171
#define IDC_CHECK_RSV_CXL               1171
#define IDC_CHECK_CHECKALL              1172
#define IDC_CHECK_RSV_NSW               1172
#define IDC_CHECK_MALE                  1173
#define IDC_STATIC_CATEGORY             1174
#define IDC_CHECK_FEMALE                1175
#define IDC_CHECK_SALEENABLE2           1176
#define IDC_CHECK_CANSMOKE              1177
#define IDC_BUTTON_COPYTO               1178
#define IDC_STATIC_REQUESTEDROOMTYPE    1179
#define IDC_STATIC_EXTBOOKINGID         1180
#define IDC_STATIC_RATEPLAN             1180
#define IDC_BUTTON_COPYTO2              1181
#define IDC_BUTTON_COPYTODETAIL         1182
#define IDC_COMBO_NATIONALITY           1183
#define IDC_BUTTON_COPYTODETAIL2        1184
#define IDC_BUTTON_NEW                  1185
#define IDC_COMBO_LANGUAGE              1186
#define IDC_COMBO_SYSTEMLANGUAGE        1187
#define IDC_CHECK_SMOKER                1188
#define IDC_COMBO_POST                  1188
#define IDC_CHECK_MARRIED               1189
#define IDC_EDIT_OPERATORNAME           1190
#define IDC_COMBO_POST2                 1190
#define IDC_COMBO_KIND                  1190
#define IDC_EDIT_TELEPHONE              1191
#define IDC_EDIT_WEBURL                 1192
#define IDC_EDIT_TELEPHONE4             1192
#define IDC_EDIT_EMAILADDRESS           1192
#define IDC_EDIT_EMAIL                  1193
#define IDC_TAB1                        1194
#define IDC_TAB_ROOM                    1194
#define IDC_TAB_CATEGORY                1194
#define IDC_TAB_BRANCH                  1195
#define IDC_EDIT_NORMALTAIMECHECKIN     1196
#define IDC_EDIT_NORMALTAIMECHECKOUT    1197
#define IDC_STATIC_BRANCHNAME           1198
#define IDC_EDIT_EXEMPTIONECI           1199
#define IDC_STATIC_ABBREVIATION         1200
#define IDC_STATIC_BRANCHCODE           1201
#define IDC_EDIT_EXEMPTIONLCO           1202
#define IDC_STATIC_ADDRESS1             1203
#define IDC_STATIC_ADDRESS2             1204
#define IDC_STATIC_TELEPHONE            1205
#define IDC_STATIC_FAX                  1206
#define IDC_STATIC_WEBURL               1207
#define IDC_CHECK_DIRECTMANAGE          1208
#define IDC_STATIC_BRANCH               1209
#define IDC_STATIC_ZIPCODE              1209
#define IDC_STATIC_FACILITYNAME         1210
#define IDC_STATIC_FACILITYCODE         1211
#define IDC_TAB_FACILITY                1212
#define IDC_EDIT_FACILITYCODE           1213
#define IDC_STATIC_NORMALTIMECHECKIN    1214
#define IDC_STATIC_MESSAGE              1215
#define IDC_STATIC_NORMALTIMECHECKOUT   1216
#define IDC_COMBO_RATEPLAN              1217
#define IDC_STATIC_EXEMPTIONECI         1218
#define IDC_EDIT_TYPENAME               1219
#define IDC_STATIC_EXEMPTIONLCO         1220
#define IDC_EDIT_NAME                   1221
#define IDC_CHECK_DAYCLOSECHARGE        1222
#define IDC_EDIT_EQUIPMENTCODE          1223
#define IDC_CHECK_HAVEEQUIPMENT         1224
#define IDC_EDIT_REGULARCAPA            1225
#define IDC_CHECK_SENDCOMFIRMATIONMAIL  1226
#define IDC_EDIT_EXTRACAPA              1227
#define IDC_CHECK_APPLYEXTENDCHARGE     1228
#define IDC_SPIN_EXTRACAPA              1229
#define IDC_CHECK_FORCEDEPOSIOCOLLECT   1230
#define IDC_SPIN_REGULARCAPA            1231
#define IDC_CHECK_NEEDCONVENTANT        1232
#define IDC_EDIT_EQUIPMENTCODE2         1233
#define IDC_EDIT_EQUIPMENTKIND          1234
#define IDC_STATIC_FACILITYKIND         1235
#define IDC_STATIC_EMAIL                1236
#define IDC_BUTTON_ADDPRODUCT           1239
#define IDC_BUTTON2                     1240
#define IDC_BUTTON_PARTICALPAYMENT      1240
#define IDC_EDIT_CATEGORYNAME           1241
#define IDC_BUTTON_ALLPAYMENT           1241
#define IDC_SPIN_SORTORDER              1242
#define IDC_BUTTON_ADDPRODUCT2          1242
#define IDC_BUTTON_ADDDEPOSIT           1242
#define IDC_STATIC_APL                  1243
#define IDC_BUTTON_ADDPRODUCT3          1243
#define IDC_BUTTON_TRANSFER             1243
#define IDC_RADIO_ATTRIBUTE1            1244
#define IDC_RADIO_ATTRIBUTE2            1245
#define IDC_RADIO_ATTRIBUTE3            1246
#define IDC_RADIO_ATTRIBUTE4            1247
#define IDC_RADIO_ATTRIBUTE5            1248
#define IDC_STATIC_ATTRIBUTE            1249
#define IDC_STATIC_TAX                  1250
#define IDC_COMBO_CURRENCY              1252
#define IDC_STATIC_RATE                 1253
#define IDC_COMBO_CURRENCY2             1253
#define IDC_COMBO_PAYMENTMETHOD         1253
#define IDC_EDIT_CURRENCYCODE           1254
#define IDC_EDIT_EXCHANGERATE           1255
#define IDC_EDIT_CASH                   1255
#define IDC_EDIT_ADPD                   1256
#define IDC_EDIT_OTHER                  1256
#define IDC_STATIC_BALANCE              1257
#define IDC_SAVECLOSE                   1258
#define IDC_EDIT_CREDITCARD             1258
#define IDC_CLOSE                       1259
#define IDC_EDIT_COUPON                 1259
#define IDC_STATIC_BALANCE2             1260
#define IDC_STATIC_REFUND               1260
#define IDC_STATIC_ROOMNUMBER           1261
#define IDC_STATIC_REFUND2              1261
#define IDC_STATIC_PFDEPOSIT            1261
#define IDC_STATIC_NAME                 1262
#define IDC_STATIC_DEPOSIT              1263
#define IDC_STATIC_HISTORY              1264
#define IDC_STATIC_TOTAL                1265
#define IDC_STATIC_MARKETSEGMENT        1265
#define IDC_STATIC_BASECURRENCY         1266
#define IDC_STATIC_WARNING              1267
#define IDC_STATIC_ROOMPANEL            1268
#define IDC_STATIC_BUSINESSDATE         1269
#define IDC_STATIC_ROOMSTATUS           1270
#define IDC_STATIC_ROOMCHANGES          1271
#define IDC_BUTTON1                     1272
#define IDC_EDIT_AGENTNAME              1273
#define IDC_EDIT_AGENTCODE              1274
#define IDC_STATIC_EMAIL1               1275
#define IDC_STATIC_EMAIL2               1276
#define IDC_STATIC_AGENTCODE            1277
#define IDC_STATIC_AGENTKIND            1278
#define IDC_COMBO_COUNTRY               1279
#define IDC_STATIC_CREDITCARDCPMPANY    1280
#define IDC_EDIT_COMPANYNAME            1281
#define IDC_STATIC_COMPANYCODE          1282
#define IDC_EDIT_COMPANYCODE            1283
#define IDC_STATIC_COMPANYCODE2         1284
#define IDC_EDIT_CLOSEDAY               1285
#define IDC_STATIC_COMPANYCODE3         1286
#define IDC_EDIT_PAYDAY                 1287
#define IDC_STATIC_COMPANYCODE4         1288
#define IDC_EDIT_RATE                   1289
#define IDC_STATIC_COMPANYCODE5         1290
#define IDC_STATIC_FIRSTNAME            1291
#define IDC_STATIC_LASTNAME             1292
#define IDC_EDIT_USERID                 1292
#define IDC_STATIC_EMPLOYEECODE         1293
#define IDC_EDIT_PASSWORD               1294
#define IDC_EDIT_CURRENT                1295
#define IDC_EDIT_NEWPASSWORD            1296
#define IDC_EDIT_NEWPASSWORD2           1297
#define IDC_BUTTON_RESETPASSWORD        1298
#define IDC_EDIT_DUTYNAME               1299
#define ID_TOOL_BST                     32771
#define ID_MASTER_OPERATORINFO          32772
#define ID_MASTER_EMPLOYEEINFO          32773
#define ID_BOOKING_ADDBOOKING           32774
#define ID_BOOKING_CUTBOOKING           32775
#define ID_BOOKING_MOVEBOOKING          32776
#define ID_BOOKING_CANCELBOOKING        32777
#define ID_VIEW_SEARCHVIEW              32778
#define ID_VIEW_BOOKINGSTATUSVIEW       32779
#define ID_FILE_NEWRESERVATION          32780
#define ID_SCH_CIN_CHECKIN              32781
#define ID_SCH_RESERVATIONVIEW          32782
#define ID_SEARCH_SEARCH                32783
#define ID_SCH_INH_CASHIER              32784
#define ID_SCH_COT_CHECKOUT             32788
#define ID_BOOKINGSTATUS_RESERVATIONVIEW 32790
#define ID_BOOKINGSTATUS_CHECKIN        32791
#define ID_BOOKINGSTATUS_INHOUSESTATUS  32792
#define ID_BOOKINGSTATUS_CHECKOUT       32793
#define ID_FILE_AAAAAAAAAAA             32794
#define TBP_ID_DCRCIN_EDIT              32795
#define ID_FILE_DIRECT                  32796
#define TBP_ID_DCRINH_EDIT              32797
#define ID_FILE_DIRECTCHECKOUT          32798
#define TBP_ID_DCRCOT_EDIT              32799
#define ID_FILE_BUSINESSDATE            32800
#define TBP_ID_BDATE_STATIC             32801
#define ID_FILE_BRANCHCOMBO             32802
#define TBP_ID_BRANCH_COMBO             32803
#define ID_FILE_FACILITYCOMBO           32804
#define TBP_ID_FACILITY_COMBO           32805
#define ID_PRICESETTING_ROOMCHARGE      32806
#define ID_RESERVATION_CHARGEDETAIL     32807
#define ID_RESERVATION_SELECTROOM       32808
#define ID_BOOKINGSTATUS_CHECKINDIRECT  32809
#define ID_BOOKINGSTATUS_CHECKOUTDIRECT 32810
#define ID_BOOKINGSTATUS_CANCELRESERVATION 32811
#define ID_BOOKINGSTATUS_CANCELRESERVATIONDIRECT 32812
#define ID_FILE_PERIODFROM              32813
#define TBP_PERIODFROM                  32814
#define ID_FILE_PERIODTO                32815
#define TBP_PERIODTO                    32816
#define ID_MASTER_BRANCHINFO            32817
#define ID_MASTER_FACILITYINFO          32818
#define ID_MASTER_EQUIPMENTTYPE         32819
#define ID_MASTER_EQUIPMENTINFO         32820
#define ID_PRICESETTING_PRODUCTSPRICE   32821
#define ID_PRICESETTING_PRODUCTSCATEGORY 32822
#define ID_SETTINGS_CURRENCYCONVERSION  32823
#define ID_SCH_DEPOSITMANAGE            32824
#define ID_CHECKIN_SELECTROOM           32825
#define ID_MASTER_CURRENCYCONVERSION    32826
#define ID_VIEW_NIGHTAUDIT              32827
#define ID_NIGHTAUDIT_CHECKIN           32828
#define ID_NIGHTAUDIT_CHECKOUT          32829
#define ID_NIGHTAUDIT_NOSHOW            32830
#define ID_NIGHTAUDIT_RESERVATION       32831
#define ID_NIGHTAUDIT_CANCELRESERVATION 32832
#define ID_VIEW_HOUSEKEEPING            32833
#define ID_MASTER_TRAVELAGENT           32834
#define ID_MASTER_CREDITCARDCOMPANY     32835
#define ID_FILE_LOGOUT                  32836
#define ID_FILE_CHANGEPASSWORD          32837
#define ID_FILE_EMPLOYEENAME            32838
#define TBP_ID_EMPNAME_STATIC           32839
#define ID_MASTER_DUTYINFO              32840
#define ID_MASTER_MARKETSEGMENT         32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1300
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
